version: 2
jobs:
  build_and_push:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Build
          command: docker build --build-arg date=$(date +%Y-%m-%dT%T%z) .
      - deploy:
          name: Push
          context: org-global
          command: |
            TAG=$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD
              docker images
            else
              echo "Not on master so not tagging"
              docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD
              IMAGE = docker images | awk {'print $3'} | sed -n 2p
              echo $IMAGE
            fi

# docker tag

#  . damacus/php-composer:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push:
          context: org-global
