version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Build
          command: docker build --build-arg date=$(date +%Y-%m-%dT%T%z) .
  push:
    docker:
      - image: circleci/build-image
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Push
          command: |
            TAG=$CIRCLE_BUILD_NUM
            docker images
# docker tag

#  . damacus/php-composer:$TAG
workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
