version: 2
jobs:
  test:
    docker:
      - image: damacus/docker-builder:latest
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Build & Test Image
          command: |
            docker-compose up -d --build
            inspec exec tests -t "docker://php-composer-builder"
            docker-compose down

  build_and_deploy:
    docker:
      - image: damacus/docker-builder:latest
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Build & Test Image
          command: |
            docker-compose up -d --build
            inspec exec tests -t "docker://php-composer-builder"
            docker-compose down
      - deploy:
          name: Push Image
          command: |
            docker login -u "${DOCKER_LOGIN:?}" -p "${DOCKER_PASSWORD:?}"
            docker-compose push php-composer-builder
            docker tag damacus/php-composer-builder:latest damacus/php-composer-builder:${CIRCLE_BUILD_NUM}
            docker push damacus/php-composer-builder:${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore:
                - master
      - build_and_deploy:
          context: org-global
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          context: org-global
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_deploy
