version: 2
jobs:
  build_and_push:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build
          command: docker build --build-arg date=$(date +%Y-%m-%dT%T%z) .
      - deploy:
          name: Push
          context: org-global
          command: |
            TAG=$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD
              docker images
            else
              echo "Not on master so not tagging"
              docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD
              IMAGE = docker images | awk {'print $3'} | sed -n 2p
              echo $IMAGE
            fi

# docker tag

#  . damacus/php-composer:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push:
          context: org-global
